// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: onboarding_service.proto

package cashloan_onboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Onboarding_GetAllLoanApplications_FullMethodName = "/cash_loan.onboarding_service.v1.Onboarding/GetAllLoanApplications"
)

// OnboardingClient is the client API for Onboarding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnboardingClient interface {
	GetAllLoanApplications(ctx context.Context, in *GetAllLoanApplicationsRequest, opts ...grpc.CallOption) (*GetAllLoanApplicationsResponse, error)
}

type onboardingClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardingClient(cc grpc.ClientConnInterface) OnboardingClient {
	return &onboardingClient{cc}
}

func (c *onboardingClient) GetAllLoanApplications(ctx context.Context, in *GetAllLoanApplicationsRequest, opts ...grpc.CallOption) (*GetAllLoanApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllLoanApplicationsResponse)
	err := c.cc.Invoke(ctx, Onboarding_GetAllLoanApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardingServer is the server API for Onboarding service.
// All implementations must embed UnimplementedOnboardingServer
// for forward compatibility.
type OnboardingServer interface {
	GetAllLoanApplications(context.Context, *GetAllLoanApplicationsRequest) (*GetAllLoanApplicationsResponse, error)
	mustEmbedUnimplementedOnboardingServer()
}

// UnimplementedOnboardingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardingServer struct{}

func (UnimplementedOnboardingServer) GetAllLoanApplications(context.Context, *GetAllLoanApplicationsRequest) (*GetAllLoanApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLoanApplications not implemented")
}
func (UnimplementedOnboardingServer) mustEmbedUnimplementedOnboardingServer() {}
func (UnimplementedOnboardingServer) testEmbeddedByValue()                    {}

// UnsafeOnboardingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardingServer will
// result in compilation errors.
type UnsafeOnboardingServer interface {
	mustEmbedUnimplementedOnboardingServer()
}

func RegisterOnboardingServer(s grpc.ServiceRegistrar, srv OnboardingServer) {
	// If the following call panics, it indicates UnimplementedOnboardingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Onboarding_ServiceDesc, srv)
}

func _Onboarding_GetAllLoanApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllLoanApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServer).GetAllLoanApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Onboarding_GetAllLoanApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServer).GetAllLoanApplications(ctx, req.(*GetAllLoanApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Onboarding_ServiceDesc is the grpc.ServiceDesc for Onboarding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Onboarding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cash_loan.onboarding_service.v1.Onboarding",
	HandlerType: (*OnboardingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllLoanApplications",
			Handler:    _Onboarding_GetAllLoanApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onboarding_service.proto",
}
