// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: onboarding_service.proto

package cashloan_onboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllLoanApplicationsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LastId                int64                  `protobuf:"varint,1,opt,name=last_id,proto3" json:"last_id,omitempty"`
	Size                  int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ZalopayId             *string                `protobuf:"bytes,3,opt,name=zalopay_id,proto3,oneof" json:"zalopay_id,omitempty"`
	LoanApplicationId     *string                `protobuf:"bytes,4,opt,name=loan_application_id,proto3,oneof" json:"loan_application_id,omitempty"`
	PartnerContractId     *string                `protobuf:"bytes,5,opt,name=partner_contract_id,proto3,oneof" json:"partner_contract_id,omitempty"`
	PartnerContractNumber *string                `protobuf:"bytes,6,opt,name=partner_contract_number,proto3,oneof" json:"partner_contract_number,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAllLoanApplicationsRequest) Reset() {
	*x = GetAllLoanApplicationsRequest{}
	mi := &file_onboarding_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLoanApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoanApplicationsRequest) ProtoMessage() {}

func (x *GetAllLoanApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoanApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllLoanApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_onboarding_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllLoanApplicationsRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GetAllLoanApplicationsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetAllLoanApplicationsRequest) GetZalopayId() string {
	if x != nil && x.ZalopayId != nil {
		return *x.ZalopayId
	}
	return ""
}

func (x *GetAllLoanApplicationsRequest) GetLoanApplicationId() string {
	if x != nil && x.LoanApplicationId != nil {
		return *x.LoanApplicationId
	}
	return ""
}

func (x *GetAllLoanApplicationsRequest) GetPartnerContractId() string {
	if x != nil && x.PartnerContractId != nil {
		return *x.PartnerContractId
	}
	return ""
}

func (x *GetAllLoanApplicationsRequest) GetPartnerContractNumber() string {
	if x != nil && x.PartnerContractNumber != nil {
		return *x.PartnerContractNumber
	}
	return ""
}

type GetAllLoanApplicationsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Data          []*GetAllLoanApplicationItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    int32                        `protobuf:"varint,2,opt,name=total_count,proto3" json:"total_count,omitempty"`
	LastId        int64                        `protobuf:"varint,3,opt,name=last_id,proto3" json:"last_id,omitempty"`
	Size          int32                        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLoanApplicationsResponse) Reset() {
	*x = GetAllLoanApplicationsResponse{}
	mi := &file_onboarding_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLoanApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoanApplicationsResponse) ProtoMessage() {}

func (x *GetAllLoanApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoanApplicationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllLoanApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_onboarding_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllLoanApplicationsResponse) GetData() []*GetAllLoanApplicationItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAllLoanApplicationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAllLoanApplicationsResponse) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GetAllLoanApplicationsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetAllLoanApplicationItem struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanApplicationId     string                 `protobuf:"bytes,2,opt,name=loan_application_id,proto3" json:"loan_application_id,omitempty"`
	ZalopayId             string                 `protobuf:"bytes,3,opt,name=zalopay_id,proto3" json:"zalopay_id,omitempty"`
	PartnerCode           string                 `protobuf:"bytes,4,opt,name=partner_code,proto3" json:"partner_code,omitempty"`
	Status                int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Code                  int32                  `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	CodeMessage           string                 `protobuf:"bytes,7,opt,name=code_message,proto3" json:"code_message,omitempty"`
	CurrentStep           string                 `protobuf:"bytes,8,opt,name=current_step,proto3" json:"current_step,omitempty"`
	PartnerContractId     string                 `protobuf:"bytes,9,opt,name=partner_contract_id,proto3" json:"partner_contract_id,omitempty"`
	PartnerContractNumber string                 `protobuf:"bytes,10,opt,name=partner_contract_number,proto3" json:"partner_contract_number,omitempty"`
	LoanAmount            int64                  `protobuf:"varint,11,opt,name=loan_amount,proto3" json:"loan_amount,omitempty"`
	LoanTerm              string                 `protobuf:"bytes,12,opt,name=loan_term,proto3" json:"loan_term,omitempty"`
	LoanInfo              string                 `protobuf:"bytes,13,opt,name=loan_info,proto3" json:"loan_info,omitempty"`
	ProductCode           string                 `protobuf:"bytes,14,opt,name=product_code,proto3" json:"product_code,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	ApprovedAmount        int64                  `protobuf:"varint,17,opt,name=approved_amount,proto3" json:"approved_amount,omitempty"`
	ApprovedAt            *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=approved_at,proto3,oneof" json:"approved_at,omitempty"`
	ApprovedTerm          string                 `protobuf:"bytes,19,opt,name=approved_term,proto3" json:"approved_term,omitempty"`
	Validation            string                 `protobuf:"bytes,20,opt,name=validation,proto3" json:"validation,omitempty"`
	SubmitInfoAt          *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=submit_info_at,proto3,oneof" json:"submit_info_at,omitempty"`
	FaceAuthenAt          *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=face_authen_at,proto3,oneof" json:"face_authen_at,omitempty"`
	SignContractAt        *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=sign_contract_at,proto3,oneof" json:"sign_contract_at,omitempty"`
	ProductLine           string                 `protobuf:"bytes,24,opt,name=product_line,proto3" json:"product_line,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAllLoanApplicationItem) Reset() {
	*x = GetAllLoanApplicationItem{}
	mi := &file_onboarding_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLoanApplicationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoanApplicationItem) ProtoMessage() {}

func (x *GetAllLoanApplicationItem) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoanApplicationItem.ProtoReflect.Descriptor instead.
func (*GetAllLoanApplicationItem) Descriptor() ([]byte, []int) {
	return file_onboarding_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllLoanApplicationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAllLoanApplicationItem) GetLoanApplicationId() string {
	if x != nil {
		return x.LoanApplicationId
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetZalopayId() string {
	if x != nil {
		return x.ZalopayId
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetPartnerCode() string {
	if x != nil {
		return x.PartnerCode
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAllLoanApplicationItem) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAllLoanApplicationItem) GetCodeMessage() string {
	if x != nil {
		return x.CodeMessage
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetPartnerContractId() string {
	if x != nil {
		return x.PartnerContractId
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetPartnerContractNumber() string {
	if x != nil {
		return x.PartnerContractNumber
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetLoanAmount() int64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *GetAllLoanApplicationItem) GetLoanTerm() string {
	if x != nil {
		return x.LoanTerm
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetLoanInfo() string {
	if x != nil {
		return x.LoanInfo
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetApprovedAmount() int64 {
	if x != nil {
		return x.ApprovedAmount
	}
	return 0
}

func (x *GetAllLoanApplicationItem) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetApprovedTerm() string {
	if x != nil {
		return x.ApprovedTerm
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

func (x *GetAllLoanApplicationItem) GetSubmitInfoAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmitInfoAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetFaceAuthenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FaceAuthenAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetSignContractAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignContractAt
	}
	return nil
}

func (x *GetAllLoanApplicationItem) GetProductLine() string {
	if x != nil {
		return x.ProductLine
	}
	return ""
}

var File_onboarding_service_proto protoreflect.FileDescriptor

const file_onboarding_service_proto_rawDesc = "" +
	"\n" +
	"\x18onboarding_service.proto\x12\x1fcash_loan.onboarding_service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x1dGetAllLoanApplicationsRequest\x12\x18\n" +
	"\alast_id\x18\x01 \x01(\x03R\alast_id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12#\n" +
	"\n" +
	"zalopay_id\x18\x03 \x01(\tH\x00R\n" +
	"zalopay_id\x88\x01\x01\x125\n" +
	"\x13loan_application_id\x18\x04 \x01(\tH\x01R\x13loan_application_id\x88\x01\x01\x125\n" +
	"\x13partner_contract_id\x18\x05 \x01(\tH\x02R\x13partner_contract_id\x88\x01\x01\x12=\n" +
	"\x17partner_contract_number\x18\x06 \x01(\tH\x03R\x17partner_contract_number\x88\x01\x01B\r\n" +
	"\v_zalopay_idB\x16\n" +
	"\x14_loan_application_idB\x16\n" +
	"\x14_partner_contract_idB\x1a\n" +
	"\x18_partner_contract_number\"\xc0\x01\n" +
	"\x1eGetAllLoanApplicationsResponse\x12N\n" +
	"\x04data\x18\x01 \x03(\v2:.cash_loan.onboarding_service.v1.GetAllLoanApplicationItemR\x04data\x12 \n" +
	"\vtotal_count\x18\x02 \x01(\x05R\vtotal_count\x12\x18\n" +
	"\alast_id\x18\x03 \x01(\x03R\alast_id\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\xfc\b\n" +
	"\x19GetAllLoanApplicationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x13loan_application_id\x18\x02 \x01(\tR\x13loan_application_id\x12\x1e\n" +
	"\n" +
	"zalopay_id\x18\x03 \x01(\tR\n" +
	"zalopay_id\x12\"\n" +
	"\fpartner_code\x18\x04 \x01(\tR\fpartner_code\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04code\x18\x06 \x01(\x05R\x04code\x12\"\n" +
	"\fcode_message\x18\a \x01(\tR\fcode_message\x12\"\n" +
	"\fcurrent_step\x18\b \x01(\tR\fcurrent_step\x120\n" +
	"\x13partner_contract_id\x18\t \x01(\tR\x13partner_contract_id\x128\n" +
	"\x17partner_contract_number\x18\n" +
	" \x01(\tR\x17partner_contract_number\x12 \n" +
	"\vloan_amount\x18\v \x01(\x03R\vloan_amount\x12\x1c\n" +
	"\tloan_term\x18\f \x01(\tR\tloan_term\x12\x1c\n" +
	"\tloan_info\x18\r \x01(\tR\tloan_info\x12\"\n" +
	"\fproduct_code\x18\x0e \x01(\tR\fproduct_code\x12:\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12(\n" +
	"\x0fapproved_amount\x18\x11 \x01(\x03R\x0fapproved_amount\x12A\n" +
	"\vapproved_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vapproved_at\x88\x01\x01\x12$\n" +
	"\rapproved_term\x18\x13 \x01(\tR\rapproved_term\x12\x1e\n" +
	"\n" +
	"validation\x18\x14 \x01(\tR\n" +
	"validation\x12G\n" +
	"\x0esubmit_info_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0esubmit_info_at\x88\x01\x01\x12G\n" +
	"\x0eface_authen_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0eface_authen_at\x88\x01\x01\x12K\n" +
	"\x10sign_contract_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x10sign_contract_at\x88\x01\x01\x12\"\n" +
	"\fproduct_line\x18\x18 \x01(\tR\fproduct_lineB\x0e\n" +
	"\f_approved_atB\x11\n" +
	"\x0f_submit_info_atB\x11\n" +
	"\x0f_face_authen_atB\x13\n" +
	"\x11_sign_contract_at2\xaa\x01\n" +
	"\n" +
	"Onboarding\x12\x9b\x01\n" +
	"\x16GetAllLoanApplications\x12>.cash_loan.onboarding_service.v1.GetAllLoanApplicationsRequest\x1a?.cash_loan.onboarding_service.v1.GetAllLoanApplicationsResponse\"\x00BAZ?gitlab.zalopay.vn/fin/lending/lending-claw/api/cashloan_onboardb\x06proto3"

var (
	file_onboarding_service_proto_rawDescOnce sync.Once
	file_onboarding_service_proto_rawDescData []byte
)

func file_onboarding_service_proto_rawDescGZIP() []byte {
	file_onboarding_service_proto_rawDescOnce.Do(func() {
		file_onboarding_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onboarding_service_proto_rawDesc), len(file_onboarding_service_proto_rawDesc)))
	})
	return file_onboarding_service_proto_rawDescData
}

var file_onboarding_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_onboarding_service_proto_goTypes = []any{
	(*GetAllLoanApplicationsRequest)(nil),  // 0: cash_loan.onboarding_service.v1.GetAllLoanApplicationsRequest
	(*GetAllLoanApplicationsResponse)(nil), // 1: cash_loan.onboarding_service.v1.GetAllLoanApplicationsResponse
	(*GetAllLoanApplicationItem)(nil),      // 2: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem
	(*timestamppb.Timestamp)(nil),          // 3: google.protobuf.Timestamp
}
var file_onboarding_service_proto_depIdxs = []int32{
	2, // 0: cash_loan.onboarding_service.v1.GetAllLoanApplicationsResponse.data:type_name -> cash_loan.onboarding_service.v1.GetAllLoanApplicationItem
	3, // 1: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.approved_at:type_name -> google.protobuf.Timestamp
	3, // 4: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.submit_info_at:type_name -> google.protobuf.Timestamp
	3, // 5: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.face_authen_at:type_name -> google.protobuf.Timestamp
	3, // 6: cash_loan.onboarding_service.v1.GetAllLoanApplicationItem.sign_contract_at:type_name -> google.protobuf.Timestamp
	0, // 7: cash_loan.onboarding_service.v1.Onboarding.GetAllLoanApplications:input_type -> cash_loan.onboarding_service.v1.GetAllLoanApplicationsRequest
	1, // 8: cash_loan.onboarding_service.v1.Onboarding.GetAllLoanApplications:output_type -> cash_loan.onboarding_service.v1.GetAllLoanApplicationsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_onboarding_service_proto_init() }
func file_onboarding_service_proto_init() {
	if File_onboarding_service_proto != nil {
		return
	}
	file_onboarding_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_onboarding_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onboarding_service_proto_rawDesc), len(file_onboarding_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onboarding_service_proto_goTypes,
		DependencyIndexes: file_onboarding_service_proto_depIdxs,
		MessageInfos:      file_onboarding_service_proto_msgTypes,
	}.Build()
	File_onboarding_service_proto = out.File
	file_onboarding_service_proto_goTypes = nil
	file_onboarding_service_proto_depIdxs = nil
}
